samples: "config/samples.tsv"
units: "config/units.tsv"

ref:
  species: homo_sapiens
  release: "115"
  build: GRCh38
  chromosome:
    - "8"
    - "22"

params:
  star:
    index:
      sjdbOverhang: 100
      extra: ""
    align:
      extra: |
        --outFilterMultimapNmax 50
        --peOverlapNbasesMin 10
        --alignSplicedMateMapLminOverLmate 0.5
        --alignSJstitchMismatchNmax 5 -1 5 5
        --chimSegmentMin 10
        --chimJunctionOverhangMin 10
        --chimScoreDropMax 30
        --chimScoreJunctionNonGTAG 0
        --chimScoreSeparation 1
        --chimSegmentReadGapMax 3
        --chimMultimapNmax 50
  arriba:
    custom_blacklist: ""
    custom_known_fusions: ""
    extra: ""
